
// appReducer
export const SET_PARAMS = 'SET_PARAMS';
export const GET_SITE_CONFIG = 'GET_SITE_CONFIG';
export const GET_THEME_CONFIG = 'GET_THEME_CONFIG';
export const POST_LOGIN_IN = 'POST_LOGIN_IN';
export const GET_MENU = 'GET_MENU';

// router
export const SET_PARAMS_ROUTER = 'SET_PARAMS_ROUTER';
export const SET_PARAMS_DATA = 'SET_PARAMS_DATA';
export const SET_PARAMS_OBJECT = 'SET_PARAMS_OBJECT';

// editorialCenter 采编中心
// export const GET_AUDITPENDING_DATA = 'GET_AUDITPENDING_DATA';
export const SET_PARAMS_CONTENT = 'SET_PARAMS_CONTENT';
// export const GET_AUDITLEVEL_DATA = 'GET_AUDITLEVEL_DATA';
export const GET_PROJECT_APP_REQUEST = 'GET_PROJECT_APP_REQUEST'; // 发布载体
export const GET_WAITING_PUBLISH_REQUEST = 'GET_WAITING_PUBLISH_REQUEST'; // 待签稿库